import unittest

from nexus_harness.runtime_common import generated_markdown


class RuntimeCommonTests(unittest.TestCase):
    def test_generated_markdown_contains_do_not_edit_marker(self):
        text = generated_markdown("body")
        self.assertIn("GENERATED BY NEXUS HARNESS", text)
        self.assertIn("DO NOT EDIT", text)
