"""Hermetic live-runtime install mapping. Never touches real ~/.codex ~/.cursor ~/.claude."""

from __future__ import annotations

import hashlib
import json
import os
import stat
import subprocess
import sys
import tempfile
import tomllib
import unittest
from pathlib import Path

from nexus_harness.install import tree_digests
from nexus_harness.runtime_common import NEXUS_EVENT_WRAPPER
from nexus_harness.runtime_install import (
    LiveInstallError,
    apply_live_install,
    inspect_live_runtime,
    plan_live_install,
    rollback_live_install,
)
from nexus_harness.runtime_claude import _HOOK_WRAPPER


REPO = Path(__file__).resolve().parents[1]


def _write(path: Path, text: str, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    os.chmod(path, mode)


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _dist(root: Path) -> Path:
    dist = root / "dist"
    (dist / "codex").mkdir(parents=True)
    (dist / "claude").mkdir(parents=True)
    (dist / "cursor").mkdir(parents=True)
    (dist / ".cursor" / "rules").mkdir(parents=True)
    (dist / "hooks").mkdir(parents=True)
    (dist / "src" / "nexus_harness").mkdir(parents=True)
    (dist / "core").mkdir(parents=True)
    _write(
        dist / "AGENTS.md",
        "<!-- GENERATED BY NEXUS HARNESS — DO NOT EDIT -->\n"
        "NEXUS WORKFLOW IS MANDATORY.\n",
    )
    _write(
        dist / "codex" / "config.toml",
        "# GENERATED BY NEXUS HARNESS — DO NOT EDIT\n"
        'sandbox_mode = "workspace-write"\n'
        'approval_policy = "on-request"\n',
    )
    _write(
        dist / "USER_RULES.md",
        "<!-- GENERATED BY NEXUS HARNESS — DO NOT EDIT -->\n"
        "NEXUS WORKFLOW IS MANDATORY.\n",
    )
    _write(
        dist / ".cursor" / "rules" / "nexus-workflow.mdc",
        "<!-- GENERATED BY NEXUS HARNESS — DO NOT EDIT -->\n"
        "NEXUS WORKFLOW IS MANDATORY.\n",
    )
    _write(
        dist / "cursor" / "sandbox.json",
        json.dumps(
            {
                "_generated_by": "GENERATED BY NEXUS HARNESS — DO NOT EDIT",
                "type": "workspace_readwrite",
            }
        )
        + "\n",
    )
    _write(
        dist / "claude" / "CLAUDE.md",
        "<!-- GENERATED BY NEXUS HARNESS — DO NOT EDIT -->\n"
        "NEXUS WORKFLOW IS MANDATORY.\n",
    )
    _write(
        dist / "claude" / "settings.json",
        json.dumps(
            {
                "hooks": {
                    "SessionStart": [
                        {
                            "hooks": [
                                {
                                    "type": "command",
                                    "command": "python3 hooks/claude_event.py --event SessionStart",
                                }
                            ]
                        }
                    ],
                    "PreToolUse": [
                        {
                            "hooks": [
                                {
                                    "type": "command",
                                    "command": "python3 hooks/claude_event.py --event PreToolUse",
                                }
                            ]
                        }
                    ],
                    "TaskCompleted": [
                        {
                            "hooks": [
                                {
                                    "type": "command",
                                    "command": (
                                        "python3 hooks/claude_event.py "
                                        "--event TaskCompleted --completion-gate"
                                    ),
                                }
                            ]
                        }
                    ],
                }
            }
        )
        + "\n",
    )
    _write(dist / "hooks" / "nexus_event.py", NEXUS_EVENT_WRAPPER)
    _write(dist / "hooks" / "claude_event.py", _HOOK_WRAPPER)
    _write(dist / "src" / "nexus_harness" / "__init__.py", "")
    _write(dist / "core" / "constitution.md", "NEXUS WORKFLOW IS MANDATORY.\n")
    return dist


def _ops(plan, destination_suffix: str | None = None) -> dict[str, str]:
    out = {}
    for item in plan.mutations:
        key = item.destination.as_posix()
        if destination_suffix:
            key = Path(item.destination).name
        out[item.artifact] = item.operation
    return out


class RuntimeInstallTests(unittest.TestCase):
    def test_plan_mode_has_zero_mutation(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            home = root / "codex-home"
            home.mkdir()
            _write(home / "config.toml", 'model = "keep"\n', 0o600)
            before = tree_digests(home)
            plan = plan_live_install(
                "codex",
                home=home,
                dist=dist,
                engine_root=root / "engine",
                backup_root=root / "backups",
            )
            self.assertFalse(plan.blocked)
            self.assertEqual(tree_digests(home), before)
            self.assertFalse((root / "engine").exists())
            self.assertFalse((root / "backups").exists())

    def test_codex_existing_config_preserved_and_nexus_keys_created(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            home = root / "codex-home"
            original = 'model = "keep"\nnotify = ["off"]\n'
            _write(home / "config.toml", original, 0o600)
            _write(home / "AGENTS.md", "# user instructions\nkeep me\n", 0o600)
            plan = plan_live_install(
                "codex",
                home=home,
                dist=dist,
                engine_root=root / "engine",
                backup_root=root / "backups",
            )
            result = apply_live_install(plan)
            self.assertTrue(result.ok)
            cfg = (home / "config.toml").read_text(encoding="utf-8")
            self.assertIn('model = "keep"', cfg)
            self.assertIn('notify = ["off"]', cfg)
            parsed = tomllib.loads(cfg)
            self.assertEqual(parsed["model"], "keep")
            self.assertEqual(parsed["sandbox_mode"], "workspace-write")
            self.assertEqual(parsed["approval_policy"], "on-request")
            self.assertEqual(stat.S_IMODE((home / "config.toml").stat().st_mode), 0o600)
            agents = (home / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("# user instructions", agents)
            self.assertIn("keep me", agents)
            self.assertIn("NEXUS_HARNESS_BEGIN", agents)
            self.assertIn("NEXUS WORKFLOW IS MANDATORY", agents)

    def test_codex_merge_is_idempotent(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            home = root / "codex-home"
            _write(home / "config.toml", 'model = "keep"\n', 0o600)
            _write(home / "AGENTS.md", "# user\n", 0o600)
            kwargs = dict(
                home=home,
                dist=dist,
                engine_root=root / "engine",
                backup_root=root / "backups",
            )
            apply_live_install(plan_live_install("codex", **kwargs))
            after_first = {
                "config": (home / "config.toml").read_bytes(),
                "agents": (home / "AGENTS.md").read_bytes(),
            }
            second = plan_live_install("codex", **kwargs)
            apply_live_install(second)
            self.assertEqual((home / "config.toml").read_bytes(), after_first["config"])
            self.assertEqual((home / "AGENTS.md").read_bytes(), after_first["agents"])
            self.assertEqual(
                (home / "AGENTS.md").read_text().count("NEXUS_HARNESS_BEGIN"), 1
            )

    def test_codex_toml_block_is_top_level_even_after_tables(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            home = root / "codex-home"
            _write(
                home / "config.toml",
                'model = "keep"\n\n[projects."/tmp/fixture"]\ntrust_level = "trusted"\n',
                0o600,
            )
            _write(home / "AGENTS.md", "# user\n", 0o600)
            apply_live_install(
                plan_live_install(
                    "codex",
                    home=home,
                    dist=dist,
                    engine_root=root / "engine",
                    backup_root=root / "backups",
                )
            )
            parsed = tomllib.loads((home / "config.toml").read_text(encoding="utf-8"))
            self.assertEqual(parsed["sandbox_mode"], "workspace-write")
            self.assertEqual(parsed["approval_policy"], "on-request")
            self.assertEqual(
                parsed["projects"]["/tmp/fixture"]["trust_level"], "trusted"
            )
            self.assertNotIn("sandbox_mode", parsed["projects"]["/tmp/fixture"])
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            home = root / "codex-home"
            _write(
                home / "config.toml",
                'sandbox_mode = "read-only"\napproval_policy = "untrusted"\n',
                0o600,
            )
            _write(home / "AGENTS.md", "# user\n", 0o600)
            apply_live_install(
                plan_live_install(
                    "codex",
                    home=home,
                    dist=dist,
                    engine_root=root / "engine",
                    backup_root=root / "backups",
                )
            )
            parsed = tomllib.loads((home / "config.toml").read_text(encoding="utf-8"))
            self.assertEqual(parsed["sandbox_mode"], "read-only")
            self.assertEqual(parsed["approval_policy"], "untrusted")

    def test_claude_unrelated_hooks_and_settings_preserved(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            home = root / "claude-home"
            settings = {
                "model": "opus",
                "permissions": {"deny": ["Bash(rm *)"]},
                "env": {"TOKEN": "must-not-drop"},
                "hooks": {
                    "PreToolUse": [
                        {
                            "hooks": [
                                {
                                    "type": "command",
                                    "command": "/tmp/keep-firewall.sh",
                                }
                            ]
                        }
                    ],
                    "SessionStart": [
                        {
                            "hooks": [
                                {
                                    "type": "command",
                                    "command": "/tmp/keep-session.sh",
                                }
                            ]
                        }
                    ],
                },
            }
            _write(home / "settings.json", json.dumps(settings, indent=2) + "\n", 0o600)
            _write(home / "CLAUDE.md", "# org rules\nkeep outside\n", 0o644)
            apply_live_install(
                plan_live_install(
                    "claude",
                    home=home,
                    dist=dist,
                    engine_root=root / "engine",
                    backup_root=root / "backups",
                )
            )
            loaded = json.loads((home / "settings.json").read_text(encoding="utf-8"))
            self.assertEqual(loaded["model"], "opus")
            self.assertEqual(loaded["permissions"], {"deny": ["Bash(rm *)"]})
            self.assertEqual(loaded["env"]["TOKEN"], "must-not-drop")
            pretool = loaded["hooks"]["PreToolUse"]
            cmds = [hook["command"] for matcher in pretool for hook in matcher["hooks"]]
            self.assertIn("/tmp/keep-firewall.sh", cmds)
            self.assertEqual(sum(1 for cmd in cmds if "claude_event.py" in cmd), 1)
            self.assertTrue(any(str(root / "engine") in cmd for cmd in cmds))
            claude_md = (home / "CLAUDE.md").read_text(encoding="utf-8")
            self.assertTrue(claude_md.startswith("# org rules\nkeep outside\n"))
            self.assertIn("NEXUS_HARNESS_BEGIN", claude_md)
            self.assertEqual(
                stat.S_IMODE((home / "settings.json").stat().st_mode), 0o600
            )

    def test_claude_hooks_deduplicated_on_second_install(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            home = root / "claude-home"
            _write(home / "settings.json", '{"hooks": {}}\n', 0o600)
            _write(home / "CLAUDE.md", "# org\n", 0o644)
            kwargs = dict(
                home=home,
                dist=dist,
                engine_root=root / "engine",
                backup_root=root / "backups",
            )
            apply_live_install(plan_live_install("claude", **kwargs))
            apply_live_install(plan_live_install("claude", **kwargs))
            loaded = json.loads((home / "settings.json").read_text(encoding="utf-8"))
            for event, matchers in loaded["hooks"].items():
                nexus = [
                    hook
                    for matcher in matchers
                    for hook in matcher.get("hooks") or []
                    if "claude_event.py" in str(hook.get("command"))
                ]
                self.assertEqual(len(nexus), 1, event)

    def test_claude_malformed_settings_fail_closed(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            home = root / "claude-home"
            _write(home / "settings.json", "{not-json", 0o600)
            _write(home / "CLAUDE.md", "# org\n", 0o644)
            before = (home / "settings.json").read_bytes()
            plan = plan_live_install(
                "claude",
                home=home,
                dist=dist,
                engine_root=root / "engine",
                backup_root=root / "backups",
            )
            self.assertTrue(plan.blocked)
            with self.assertRaises(LiveInstallError):
                apply_live_install(plan)
            self.assertEqual((home / "settings.json").read_bytes(), before)

    def test_claude_md_duplicate_blocks_conflict(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            home = root / "claude-home"
            _write(
                home / "CLAUDE.md",
                "<!-- NEXUS_HARNESS_BEGIN -->\na\n<!-- NEXUS_HARNESS_END -->\n"
                "<!-- NEXUS_HARNESS_BEGIN -->\nb\n<!-- NEXUS_HARNESS_END -->\n",
            )
            _write(home / "settings.json", '{"hooks": {}}\n', 0o600)
            plan = plan_live_install(
                "claude",
                home=home,
                dist=dist,
                engine_root=root / "engine",
                backup_root=root / "backups",
            )
            self.assertTrue(plan.blocked)
            self.assertTrue(
                any(item.operation == "CONFLICT" for item in plan.mutations)
            )

    def test_cursor_does_not_invent_unsupported_global_targets(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            home = root / "cursor-home"
            home.mkdir()
            _write(home / "cli-config.json", '{"sandbox": {"mode": "disabled"}}\n')
            project = root / "project"
            project.mkdir()
            plan = plan_live_install(
                "cursor",
                home=home,
                dist=dist,
                engine_root=root / "engine",
                project_root=project,
                backup_root=root / "backups",
            )
            scopes = {item.artifact: item.scope for item in plan.mutations}
            self.assertEqual(scopes["USER_RULES.md"], "NOT_APPLICABLE")
            self.assertEqual(scopes["cursor/sandbox.json"], "NEXUS_INTERNAL_ONLY")
            self.assertEqual(
                scopes[".cursor/rules/nexus-workflow.mdc"], "PROJECT_SUPPORTED"
            )
            apply_live_install(plan)
            self.assertFalse((home / "USER_RULES.md").exists())
            self.assertFalse((home / "sandbox.json").exists())
            self.assertFalse((home / "cursor").exists())
            self.assertTrue(
                (project / ".cursor" / "rules" / "nexus-workflow.mdc").is_file()
            )
            cli = json.loads((home / "cli-config.json").read_text(encoding="utf-8"))
            self.assertEqual(cli["sandbox"]["mode"], "disabled")

    def test_rollback_restores_exact_bytes_and_modes(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            home = root / "codex-home"
            _write(home / "config.toml", 'model = "keep"\n', 0o600)
            _write(home / "AGENTS.md", "# user\n", 0o600)
            before_cfg = (home / "config.toml").read_bytes()
            before_agents = (home / "AGENTS.md").read_bytes()
            before_mode = stat.S_IMODE((home / "config.toml").stat().st_mode)
            result = apply_live_install(
                plan_live_install(
                    "codex",
                    home=home,
                    dist=dist,
                    engine_root=root / "engine",
                    backup_root=root / "backups",
                )
            )
            self.assertNotEqual((home / "config.toml").read_bytes(), before_cfg)
            rollback_live_install(result)
            self.assertEqual((home / "config.toml").read_bytes(), before_cfg)
            self.assertEqual((home / "AGENTS.md").read_bytes(), before_agents)
            self.assertEqual(
                stat.S_IMODE((home / "config.toml").stat().st_mode), before_mode
            )

    def test_hook_paths_work_from_arbitrary_cwd(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            src = dist / "src" / "nexus_harness"
            # Real dispatch is required for a successful import path.
            import shutil

            shutil.rmtree(src)
            shutil.copytree(REPO / "src" / "nexus_harness", src)
            home = root / "claude-home"
            _write(home / "settings.json", '{"hooks": {}}\n', 0o600)
            _write(home / "CLAUDE.md", "# org\n", 0o644)
            engine = root / "engine"
            apply_live_install(
                plan_live_install(
                    "claude",
                    home=home,
                    dist=dist,
                    engine_root=engine,
                    backup_root=root / "backups",
                )
            )
            hook = engine / "hooks" / "claude_event.py"
            elsewhere = root / "elsewhere"
            elsewhere.mkdir()
            completed = subprocess.run(
                [sys.executable, str(hook), "--event", "SessionStart"],
                cwd=elsewhere,
                input="{}",
                text=True,
                capture_output=True,
            )
            self.assertEqual(completed.returncode, 0, completed.stderr)
            loaded = json.loads((home / "settings.json").read_text(encoding="utf-8"))
            commands = [
                hook["command"]
                for matchers in loaded["hooks"].values()
                for matcher in matchers
                for hook in matcher["hooks"]
                if "claude_event.py" in hook["command"]
            ]
            self.assertTrue(commands)
            for command in commands:
                self.assertIn(str(engine.resolve()), command)
                self.assertFalse(command.startswith("python3 hooks/claude_event.py"))

    def test_inspect_does_not_require_secrets_and_classifies_cursor_scopes(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            home = root / "cursor-home"
            home.mkdir()
            report = inspect_live_runtime("cursor", home)
            self.assertEqual(report["home"], str(home.resolve()))
            self.assertIn("artifacts", report)
            self.assertEqual(
                report["artifacts"]["USER_RULES.md"]["scope"], "NOT_APPLICABLE"
            )


class CliRuntimeInstallTests(unittest.TestCase):
    def test_runtime_install_plan_json_has_zero_mutation(self):
        from tests.test_cli import _run_main

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            dist = _dist(root)
            home = root / "codex-home"
            home.mkdir()
            _write(home / "config.toml", 'model = "keep"\n', 0o600)
            before = _digest(home / "config.toml")
            code, stdout, stderr = _run_main(
                [
                    "--json",
                    "runtime",
                    "install",
                    "codex",
                    "--plan",
                    "--home",
                    str(home),
                    "--dist",
                    str(dist),
                    "--engine-root",
                    str(root / "engine"),
                    "--backup-root",
                    str(root / "backups"),
                ]
            )
            self.assertEqual(code, 0, stderr + stdout)
            payload = json.loads(stdout)
            self.assertEqual(payload["runtime"], "codex")
            self.assertFalse(payload["blocked"])
            self.assertEqual(_digest(home / "config.toml"), before)
            self.assertFalse((root / "engine").exists())


if __name__ == "__main__":
    unittest.main()
