import hashlib
import json
import tempfile
import tomllib
import unittest
from pathlib import Path
from unittest.mock import patch

from nexus_harness.install import (
    atomic_install,
    detect_drift,
    rollback_install,
    tree_digests,
)


class InstallTests(unittest.TestCase):
    def test_existing_install_is_backed_up_before_replace(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "dist"
            target = root / "installed"
            source.mkdir()
            target.mkdir()
            (source / "a").write_text("new")
            (target / "a").write_text("old")

            backup = atomic_install(source, target)

            self.assertEqual((target / "a").read_text(), "new")
            self.assertEqual((backup / "a").read_text(), "old")

    def test_user_owned_file_survives_replacement(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "dist"
            target = root / "installed"
            source.mkdir()
            target.mkdir()
            (source / "generated.txt").write_text("generated")
            (target / "generated.txt").write_text("old")
            (target / "user.txt").write_text("keep")

            atomic_install(source, target)

            self.assertEqual((target / "generated.txt").read_text(), "generated")
            self.assertEqual((target / "user.txt").read_text(), "keep")

    def test_failed_final_rename_restores_current_install(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "dist"
            target = root / "installed"
            source.mkdir()
            target.mkdir()
            (source / "a").write_text("new")
            (target / "a").write_text("old")

            real_replace = __import__("os").replace

            def fail_staging_rename(old, new):
                if Path(old).name.startswith(".installed.staging-"):
                    raise OSError("simulated rename failure")
                return real_replace(old, new)

            with patch(
                "nexus_harness.install.os.replace", side_effect=fail_staging_rename
            ):
                with self.assertRaises(OSError):
                    atomic_install(source, target)

            self.assertEqual((target / "a").read_text(), "old")

    def test_drift_classifies_missing_modified_and_extra(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            installed = root / "installed"
            installed.mkdir()
            (installed / "same").write_text("same")
            (installed / "changed").write_text("changed")
            (installed / "extra").write_text("# GENERATED BY NEXUS HARNESS\nextra")
            lock = {
                "generated_hashes": {
                    "dist/same": hashlib.sha256(b"same").hexdigest(),
                    "dist/changed": hashlib.sha256(b"original").hexdigest(),
                    "dist/missing": hashlib.sha256(b"missing").hexdigest(),
                }
            }

            report = detect_drift(installed, lock)

            self.assertEqual(report.missing, ("missing",))
            self.assertEqual(report.modified, ("changed",))
            self.assertEqual(report.extra, ("extra",))
            self.assertTrue(report.has_drift)

    def test_user_file_and_gitkeep_are_not_extra(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            installed = root / "installed"
            installed.mkdir()
            (installed / "generated").write_text("generated")
            (installed / "notes.txt").write_text("user-owned")
            (installed / ".gitkeep").write_text("")
            lock = {
                "generated_hashes": {
                    "dist/generated": hashlib.sha256(b"generated").hexdigest(),
                }
            }

            report = detect_drift(installed, lock)

            self.assertEqual(report.extra, ())
            self.assertFalse(report.has_drift)

    def test_drift_is_clean_for_matching_install(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            installed = root / "installed"
            installed.mkdir()
            (installed / "a").write_text("content")
            lock_path = root / "harness.lock"
            lock_path.write_text(
                json.dumps(
                    {
                        "generated_hashes": {
                            "dist/a": hashlib.sha256(b"content").hexdigest()
                        }
                    }
                )
            )

            report = detect_drift(installed, lock_path)

            self.assertFalse(report.has_drift)

    def test_symlink_source_is_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            real = root / "real"
            real.mkdir()
            (real / "a").write_text("new")
            source = root / "dist"
            source.symlink_to(real)
            target = root / "installed"
            from nexus_harness.safe import PathSafetyError

            with self.assertRaises(PathSafetyError):
                atomic_install(source, target)

    def test_rollback_restores_previous_tree_byte_for_byte(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            first = root / "v1"
            second = root / "v2"
            target = root / "installed"
            first.mkdir()
            second.mkdir()
            (first / "a").write_text("old-a")
            (first / "nested").mkdir()
            (first / "nested" / "b").write_text("old-b")
            (second / "a").write_text("new-a")
            (second / "nested").mkdir()
            (second / "nested" / "b").write_text("new-b")
            (second / "c").write_text("extra")

            atomic_install(first, target)
            before = tree_digests(target)
            backup = atomic_install(second, target)
            self.assertNotEqual(tree_digests(target), before)
            displaced = rollback_install(backup, target)
            self.assertEqual(tree_digests(target), before)
            self.assertEqual((displaced / "a").read_text(), "new-a")

    def test_disposable_home_install_parses_adapters_and_never_touches_real_homes(self):
        home = Path.home()
        real_homes = (home / ".claude", home / ".cursor", home / ".codex")
        before_mtime = {
            path: path.stat().st_mtime if path.exists() else None for path in real_homes
        }
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "dist"
            target = root / "runtime-home"
            source.mkdir()
            (source / "claude").mkdir()
            (source / "cursor").mkdir()
            (source / "codex").mkdir()
            (source / ".cursor" / "rules").mkdir(parents=True)
            (source / "claude" / "CLAUDE.md").write_text(
                "# GENERATED BY NEXUS HARNESS\n"
            )
            (source / "claude" / "settings.json").write_text('{"hooks": {}}')
            (source / "USER_RULES.md").write_text("# GENERATED BY NEXUS HARNESS\n")
            (source / ".cursor" / "rules" / "nexus-workflow.mdc").write_text(
                "# GENERATED BY NEXUS HARNESS\n"
            )
            (source / "cursor" / "sandbox.json").write_text(
                '{"type":"workspace_readwrite","networkPolicy":{"default":"deny"}}'
            )
            (source / "codex" / "config.toml").write_text(
                'sandbox_mode = "workspace-write"\napproval_policy = "on-request"\n'
            )
            (source / "AGENTS.md").write_text("NEXUS WORKFLOW IS MANDATORY\n")
            target.mkdir()
            (target / "stale.txt").write_text("previous")

            backup = atomic_install(source, target)
            settings = json.loads((target / "claude" / "settings.json").read_text())
            sandbox = json.loads((target / "cursor" / "sandbox.json").read_text())
            config = tomllib.loads((target / "codex" / "config.toml").read_text())
            self.assertIn("hooks", settings)
            self.assertEqual(sandbox["type"], "workspace_readwrite")
            self.assertEqual(config["sandbox_mode"], "workspace-write")
            self.assertTrue(str(target).startswith(tmp))
            for path in real_homes:
                self.assertNotEqual(path.resolve(), target.resolve())
                after = path.stat().st_mtime if path.exists() else None
                self.assertEqual(after, before_mtime[path])

            previous = tree_digests(backup)
            rollback_install(backup, target)
            self.assertEqual(tree_digests(target), previous)
            self.assertEqual((target / "stale.txt").read_text(), "previous")


if __name__ == "__main__":
    unittest.main()
