import io
import json
import importlib.util
import sys
import types
import unittest
from unittest.mock import patch
from pathlib import Path

from nexus_harness.runtime_claude import render


class ClaudeAdapterTests(unittest.TestCase):
    def setUp(self):
        self.files = {
            item.relative_path: item.content.decode("utf-8")
            for item in render(Path("."))
        }

    def test_claude_output_has_completion_and_prompt_hooks(self):
        settings = self.files["claude/settings.json"]
        self.assertIn("UserPromptSubmit", settings)
        self.assertIn("TaskCompleted", settings)
        self.assertNotIn("ssh ", settings.lower())

    def test_all_required_events_are_wired(self):
        settings = json.loads(self.files["claude/settings.json"])
        self.assertEqual(
            set(settings["hooks"]),
            {
                "SessionStart",
                "UserPromptSubmit",
                "PreToolUse",
                "PostToolUseFailure",
                "PostToolBatch",
                "TaskCompleted",
                "Stop",
                "PreCompact",
                "PostCompact",
                "ConfigChange",
                "SessionEnd",
            },
        )

    def test_constitution_is_minimal_and_points_to_canonical_memory(self):
        constitution = self.files["claude/CLAUDE.md"]
        self.assertIn("Nexus Memory", constitution)
        self.assertIn("completion gate", constitution.lower())
        self.assertIn("GENERATED BY NEXUS HARNESS", constitution)

    def test_generated_output_has_no_machine_or_memory_leakage(self):
        output = "\n".join(self.files.values()).lower()
        for forbidden in (
            "/users/",
            "ssh ",
            "claude-sonnet",
            "claude-mem",
            "raw memory",
        ):
            self.assertNotIn(forbidden, output)

    def test_compaction_order_is_explicit(self):
        output = "\n".join(self.files.values())
        self.assertIn("checkpoint_memory_candidates", output)
        self.assertIn("restore_memory_candidates", output)
        self.assertIn("PreCompact", output)
        self.assertIn("SessionStart", output)

    def test_task_completed_documents_exit_two_on_gate_failure(self):
        output = "\n".join(self.files.values())
        self.assertIn("completion gate", output.lower())
        self.assertIn("exit 2", output.lower())

    def _load_wrapper(self):
        module_spec = importlib.util.spec_from_file_location(
            "claude_event", Path("hooks/claude_event.py")
        )
        wrapper = importlib.util.module_from_spec(module_spec)
        module_spec.loader.exec_module(wrapper)
        return wrapper

    def test_completion_hook_propagates_dispatch_exit_code(self):
        wrapper = self._load_wrapper()
        common_hooks = types.ModuleType("nexus_harness.hooks")
        common_hooks.dispatch = lambda event, payload, completion_gate=False: 2
        with patch.dict(sys.modules, {"nexus_harness.hooks": common_hooks}):
            with patch.object(
                sys,
                "argv",
                ["claude_event.py", "--event", "TaskCompleted", "--completion-gate"],
            ):
                with patch.object(sys, "stdin", io.StringIO("{}")):
                    self.assertEqual(wrapper.main(), 2)

    def test_invalid_json_with_completion_gate_exits_two(self):
        wrapper = self._load_wrapper()
        with patch.object(
            sys,
            "argv",
            ["claude_event.py", "--event", "TaskCompleted", "--completion-gate"],
        ):
            with patch.object(sys, "stdin", io.StringIO("not-json")):
                self.assertEqual(wrapper.main(), 2)

    def test_unexpected_dispatch_failure_is_nonzero_without_completion_gate(self):
        wrapper = self._load_wrapper()
        common_hooks = types.ModuleType("nexus_harness.hooks")

        def boom(*_args, **_kwargs):
            raise RuntimeError("unexpected policy failure")

        common_hooks.dispatch = boom
        with patch.dict(sys.modules, {"nexus_harness.hooks": common_hooks}):
            with patch.object(
                sys, "argv", ["claude_event.py", "--event", "SessionStart"]
            ):
                with patch.object(sys, "stdin", io.StringIO("{}")):
                    code = wrapper.main()
        self.assertNotEqual(code, 0)
        self.assertEqual(code, 1)

    def test_rendered_wrapper_matches_source_wrapper(self):
        self.assertEqual(
            self.files["hooks/claude_event.py"],
            Path("hooks/claude_event.py").read_text(encoding="utf-8"),
        )
