import json
import unittest
from pathlib import Path

from nexus_harness.runtime_claude import render


class ClaudeAdapterTests(unittest.TestCase):
    def setUp(self):
        self.files = {
            item.relative_path: item.content.decode("utf-8")
            for item in render(Path("."))
        }

    def test_claude_output_has_completion_and_prompt_hooks(self):
        settings = self.files["claude/settings.json"]
        self.assertIn("UserPromptSubmit", settings)
        self.assertIn("TaskCompleted", settings)
        self.assertNotIn("ssh ", settings.lower())

    def test_all_required_events_are_wired(self):
        settings = json.loads(self.files["claude/settings.json"])
        self.assertEqual(
            set(settings["hooks"]),
            {
                "SessionStart",
                "UserPromptSubmit",
                "PreToolUse",
                "PostToolUseFailure",
                "PostToolBatch",
                "TaskCompleted",
                "Stop",
                "PreCompact",
                "PostCompact",
                "ConfigChange",
                "SessionEnd",
            },
        )

    def test_constitution_is_minimal_and_points_to_canonical_memory(self):
        constitution = self.files["claude/CLAUDE.md"]
        self.assertIn("Nexus Memory", constitution)
        self.assertIn("completion gate", constitution.lower())
        self.assertIn("GENERATED BY NEXUS HARNESS", constitution)

    def test_generated_output_has_no_machine_or_memory_leakage(self):
        output = "\n".join(self.files.values()).lower()
        for forbidden in (
            "/users/",
            "ssh ",
            "claude-sonnet",
            "claude-mem",
            "raw memory",
        ):
            self.assertNotIn(forbidden, output)

    def test_compaction_order_is_explicit(self):
        output = "\n".join(self.files.values())
        self.assertIn("checkpoint_memory_candidates", output)
        self.assertIn("restore_memory_candidates", output)
        self.assertIn("PreCompact", output)
        self.assertIn("SessionStart", output)

    def test_task_completed_documents_exit_two_on_gate_failure(self):
        output = "\n".join(self.files.values())
        self.assertIn("completion gate", output.lower())
        self.assertIn("exit 2", output.lower())
