# GENERATED BY NEXUS HARNESS — DO NOT EDIT
"""Claude event bridge; lifecycle logic remains runtime-neutral."""

from __future__ import annotations

import argparse
import sys


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--event", required=True)
    parser.add_argument("--completion-gate", action="store_true")
    args = parser.parse_args()
    try:
        from nexus_harness.hooks import dispatch
    except ImportError:
        # The common hook engine is installed by the hooks integration task.
        return 0
    try:
        dispatch(args.event, completion_gate=args.completion_gate)
    except Exception:
        if args.completion_gate:
            return 2
        return 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
