"""Shared helpers for deterministic, generated runtime files."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


GENERATED_MARKER = "GENERATED BY NEXUS HARNESS — DO NOT EDIT"
_HOOK_COMMAND = "python3 hooks/nexus_event.py --event"


def _normalize_newlines(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n").rstrip("\n") + "\n"


def generated_markdown(body: str) -> str:
    """Return Markdown with the canonical generated-file ownership marker."""
    return _normalize_newlines(f"<!-- {GENERATED_MARKER} -->\n{body}")


def generated_json(data: Any) -> str:
    """Serialize JSON deterministically and include the ownership marker."""
    if isinstance(data, dict):
        payload = {**data, "_generated_by": GENERATED_MARKER}
    else:
        payload = {"_generated_by": GENERATED_MARKER, "data": data}
    return _normalize_newlines(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
    )


def generated_toml_header() -> str:
    """Return the canonical ownership header for TOML files."""
    return f"# {GENERATED_MARKER}\n"


def load_constitution(root: Path | None = None) -> str:
    if root is not None:
        candidate = Path(root) / "core" / "constitution.md"
        if candidate.is_file():
            return candidate.read_text(encoding="utf-8").rstrip()
    fallback = Path(__file__).resolve().parents[2] / "core" / "constitution.md"
    return fallback.read_text(encoding="utf-8").rstrip()


def constitution_with_notes(root: Path | None, notes: str) -> str:
    body = load_constitution(root)
    extra = notes.strip()
    if extra:
        return f"{body}\n\n{extra}"
    return body


NEXUS_EVENT_WRAPPER = (
    f"# {GENERATED_MARKER}\n"
    + '''"""Runtime-neutral Nexus event entrypoint."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys

NEXUS_HOME = Path(__file__).resolve().parents[1]
os.environ["NEXUS_HOME"] = str(NEXUS_HOME)
sys.path.insert(0, str(NEXUS_HOME / "src"))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--event", required=True)
    parser.add_argument("--completion-gate", action="store_true")
    args = parser.parse_args()
    raw = sys.stdin.read().strip()
    try:
        payload = json.loads(raw) if raw else {}
    except json.JSONDecodeError:
        return 2 if args.completion_gate else 1
    try:
        from nexus_harness.hooks import dispatch
    except ImportError:
        return 2 if args.completion_gate else 0
    try:
        result = dispatch(args.event, payload, completion_gate=args.completion_gate)
    except Exception:
        return 2 if args.completion_gate else 1
    if result is None:
        return 2 if args.completion_gate else 0
    if getattr(result, "output", None) is not None:
        print(json.dumps(result.output, default=str))
    exit_code = getattr(result, "exit_code", result)
    try:
        return int(exit_code)
    except (TypeError, ValueError):
        return 2 if args.completion_gate else 0


if __name__ == "__main__":
    sys.exit(main())
'''
)
