"""Shared helpers for deterministic, generated runtime files."""

from __future__ import annotations

import json
from typing import Any


GENERATED_MARKER = "GENERATED BY NEXUS HARNESS — DO NOT EDIT"


def _normalize_newlines(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n").rstrip("\n") + "\n"


def generated_markdown(body: str) -> str:
    """Return Markdown with the canonical generated-file ownership marker."""
    return _normalize_newlines(f"<!-- {GENERATED_MARKER} -->\n{body}")


def generated_json(data: Any) -> str:
    """Serialize JSON deterministically and include the ownership marker."""
    if isinstance(data, dict):
        payload = {**data, "_generated_by": GENERATED_MARKER}
    else:
        payload = {"_generated_by": GENERATED_MARKER, "data": data}
    return _normalize_newlines(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
    )


def generated_toml_header() -> str:
    """Return the canonical ownership header for TOML files."""
    return f"# {GENERATED_MARKER}\n"
